AWSTemplateFormatVersion: 2010-09-09
Description: This template will create s3 bucket that host meta data for MMLand NFTs
Parameters:
  
Resources:
  MMLandBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mymeta-store-token-meta-bucket-development
      Tags:
        - Key: Application Name
          Value: MyMetaStore
      