AWSTemplateFormatVersion: 2010-09-09
Description: This template will create EC2 instance and RDS that host my meta api server
Parameters:
  ApiDbName:
    Type: String
    Default: mymetadb
  EnvironmentName:
    Type: String
    AllowedValues:
      - development
      - staging
      - production
    Default: development
Resources:
  ApiInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0cff7528ff583bf9a
      KeyName: MyMetaApiInstance
      SecurityGroups:
        - !Ref ApiInstanceSG
  ApiInstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: For Api server security group
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
  ApiDb:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref ApiDbName
      MasterUsername: mymetadb
      MasterUserPassword: 123qweQWE
      Engine: MySQL
      DBInstanceClass: db.t2.micro
      StorageType: gp2
      PubliclyAccessible: True
      AllocatedStorage: "20"
      DBInstanceIdentifier: !Join 
        - "-"
        - - mymeta
          - db
          - !Ref EnvironmentName
      DBSecurityGroups:
        - !Ref ApiDbSG
  ApiDbSG:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      GroupDescription: Security Group for RDS public access
      DBSecurityGroupIngress:
        - CIDRIP: 0.0.0.0/0